stages:
  - build
  - test

build:
  stage: build
  services:
    - docker:dind
  script:
      - apt-get update
      - apt-get install -y docker.io
      - sudo docker build -t my-k6-test .
    
test_job:
  stage: test
  script: 
    - sudo docker run my-k6-test